# Generated by Django 2.2.10 on 2020-07-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200731_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
    ]
